branches-template:
  main: "{{run_id}}"
  feature*: "{{ref}}.{{timestamp}}"
  release*: "{{name}}.{{timestamp}}"
  develop: "SNAPSHOT-{{timestamp}}"
  tag: "{{ref}}"
dist-tags:
  main: "latest"
  release*: "RELEASE"
  develop: "dev"
  tag: "tag"

