branches-template:
  main: "{{ ref }}"
  feature*: "{{ref}}.{{timestamp}}"
  release*: "{{name}}.{{timestamp}}"
  develop: "SNAPSHOT-{{combine}}"
  tags: "{{ref}}"
tags:
  main: "latest"
  release: "RELEASE"
  develop: "dev"

