branches-template:
  main: "{{ ref }}"
  feature*: "{{ref}}.{{timestamp}}"
  release*: "{{name}}.{{timestamp}}"
  develop: "SNAPSHOT-{{combine}}"
  tags: "{{ref}}"
dist-tags:
  main: "latest"
  release*: "RELEASE"
  develop: "dev"
  tag: "tag"

