name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Github Metadata action
          uses: nookyo/qubership-workflow-hub/actions/github-metadata@main
          with:
            branch-template: '{
                                "main":"{{name}}.{{combine}}",
                                "release":"v{{major}}.{{minor}}.{{patch}}",
                                "dev":"SNAPSHOT-{{combine}}"
                              }'
            dist-tags: '{
                          "main":"master",
                          "develop":"next",
                          "release":"latest"
                        }'



                # main: {{ref_name}}.{{sha}}
                # release: v{{major}}.{{minor}}.{{patch}}
                # develop: SNAPSHOT-{{combine}}


