name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Github Metadata action
          uses: nookyo/qubership-workflow-hub/actions/github-metadata@main
          id: metadata

        - name:
          run: echo "rendered = ${{ steps.metadata.outputs.result }}"
