name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Meta Extractor
          uses: nookyo/qubership-workflow-hub/actions/github-metadata@main
          with:
            default-template: 'SNAPSHOT-{{combine}}-v{{major}}.{{minor}}.{{patch}}-{{tag}}-{{ sha }}'
            branch-templates: |
                main: "{{ major }}.{{ minor }}.{{ patch }}-({{ combine }})"
                develop: "SNAPSHOT-{{ combine }}"
